services:
  argos_ui_prod:
    image: argos-ui-prod:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:82"
    volumes:
      - .:/app
      - /app/node_modules
