FROM node:20 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG VITE_FILE_MANAGER_API_BASE_URL
ARG VITE_ARGOS_API_BASE_URL

RUN test -n "$VITE_FILE_MANAGER_API_BASE_URL" || (echo "Error: VITE_FILE_MANAGER_API_BASE_URL cannot be empty" && exit 1)
RUN test -n "$VITE_ARGOS_API_BASE_URL" || (echo "Error: VITE_ARGOS_API_BASE_URL cannot be empty" && exit 1)

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
