services:
  argos_ui_prod:
    image: argoscs/ui:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        VITE_ARGOS_API_BASE_URL: ${VITE_ARGOS_API_BASE_URL}
        VITE_FILE_MANAGER_API_BASE_URL: ${VITE_FILE_MANAGER_API_BASE_URL}
    ports:
      - "5175:80"
    volumes:
      - .:/app
      - /app/node_modules
