module.exports = {
  overrides: [
    {
      files: ["*.ts", "*.tsx", "*.js"],
      options: {
        arrowParens: "always",
        bracketSpacing: true,
        endOfLine: "lf",
        htmlWhitespaceSensitivity: "css",
        insertPragma: false,
        singleAttributePerLine: false,
        bracketSameLine: false,
        jsxSingleQuote: false,
        printWidth: 80,
        proseWrap: "preserve",
        quoteProps: "as-needed",
        requirePragma: false,
        semi: true,
        singleQuote: false,
        tabWidth: 2,
        trailingComma: "es5",
        useTabs: false,
        embeddedLanguageFormatting: "auto",
        vueIndentScriptAndStyle: false,
        experimentalTernaries: false,
        parser: "typescript",
      },
    },
    {
      files: "*.css",
      options: {
        arrowParens: "always",
        bracketSpacing: true,
        endOfLine: "lf",
        htmlWhitespaceSensitivity: "css",
        insertPragma: false,
        singleAttributePerLine: false,
        bracketSameLine: false,
        printWidth: 80,
        proseWrap: "preserve",
        quoteProps: "as-needed",
        requirePragma: false,
        semi: true,
        singleQuote: false,
        tabWidth: 2,
        trailingComma: "es5",
        useTabs: false,
        embeddedLanguageFormatting: "auto",
        vueIndentScriptAndStyle: false,
        experimentalTernaries: false,
        parser: "css",
      },
    },
  ],
};
