sonar.projectKey=argos-ui
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/*.d.ts,**/*.json,**/build/**,**/src/setupTests.ts,**/src/App.tsx