export enum COLORS {
  PRIMARY_DEFAULT = "#2A2F40",
  PRIMARY_ACTION = "#1D212F",
  PRIMARY_HOVER = "#12141D",
  SECONDARY = "#D8B4FE",
  LINK = "#93C5FD",
  NEUTRAL_WHITE = "#FFF",
  NEUTRAL_BLACK = "#000",
  ERROR = "#FCA5A5",
  SUCCESS = "#86EFAC",
  WARNING_DEFAULT = "#FEF08A",
  WARNING_HEAVY = "#FDBA74",
  WARNING_CRITICAL = "#D97706",
}
